### ISSUE TITLE
Adding custom infills does not work.

### ISSUE THREAD

**Issue by MorningOfTheSky** [Ultimaker/CuraEngine_plugin_infill_generate#14]
I tried created a custom infill of a pixelated heart, but it did not work. I don't know if my syntax for the .wkt file was wrong, or the feature isn't available yet. It would be nice to know! I also can't attach the .wkt file, but if you would like it, I can find a way to attach it. Thanks!

**Comment by jellespijker** [comment]
can you share the wkt file?

**Comment by MorningOfTheSky** [comment]
[Heart Test.wkt.zip](https://github.com/Ultimaker/CuraEngine_plugin_infill_generate/files/15237207/Heart.Test.wkt.zip)

Here is the file.

**Comment by EmJay276** [comment]
You need to add an additional Polygon (hexagonal or square) at the top of the file thats the outer contour to multiply the tile
