### ISSUE TITLE
[FR] add "Triangle Star", "Hexa Star" and "Start" as tiles

### ISSUE THREAD

**Issue by jellespijker** [Ultimaker/CuraEngine_plugin_infill_generate#8]
@5axes made some really nice tiles which in my opinion would make a valuable addition for this plugin. https://community.ultimaker.com/topic/44394-cura-55-plugin-curaengine_plugin_infill_generate/

Can we use these new tiles in the next minor release of the plugin @5axes? I can create the PR myself and co-author you.

[hexa_star.zip](https://github.com/Ultimaker/CuraEngine_plugin_infill_generate/files/13296872/hexa_star.zip)
[tiles.zip](https://github.com/Ultimaker/CuraEngine_plugin_infill_generate/files/13296873/tiles.zip)

**Comment by 5axes** [comment]
Fill free to use these files. No need to mention me as author it was jus an exercice to test the new possibilities open by your plugin.

**Comment by jellespijker** [comment]
Thx, and I really love the creativity of the different kind of "User" tiles I see pop up on the socials already
